# Generated by Django 3.1.5 on 2021-01-08 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodiesfoods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodiesfoods.food')),
            ],
            options={
                'verbose_name_plural': 'Food requests',
            },
        ),
    ]
