# Generated by Django 3.1.5 on 2021-01-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodiesfoods', '0002_foodrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodrequest',
            options={'verbose_name_plural': 'Food Requests'},
        ),
    ]
